<?php

/**
 * Plugin Name:       Icon Library
 * Description:       Gutenberg block that inserts SVG icons from a sprite file (ico.svg) via <use> and links them.
 * Version:           0.1.0
 * Requires at least: 6.6
 * Requires PHP:      8.3
 * Author:            svgforge
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       icon-library
 * Domain Path:       /languages
 */
defined('ABSPATH') || exit;

/**
 * Loads the settings page (SVG upload).
 */
require_once __DIR__ . '/src/admin/admin.php';

/**
 * Returns the URL of the SVG sprite file.
 *
 * Source order:
 *  1. Uploaded file from the settings (backend upload).
 *  2. Filter icon_library_sprite_url (e.g. theme override, CDN).
 *  3. Fallback: sprite.svg bundled with the plugin.
 *
 * @return string
 */
function icon_library_sprite_url()
{
    $uploaded = function_exists('icon_library_uploaded_sprite_url') ? icon_library_uploaded_sprite_url() : '';

    if ($uploaded !== '') {
        $data = function_exists('icon_library_uploaded_sprite_data') ? icon_library_uploaded_sprite_data() : [];

        if (isset($data['time']) && (int) $data['time'] > 0) {
            return add_query_arg('m', (int) $data['time'], $uploaded);
        }

        return $uploaded;
    }

    $filtered = (string) apply_filters('icon_library_sprite_url', '');

    if ($filtered !== '') {
        return $filtered;
    }

    return plugins_url('sprite.svg', __FILE__);
}

/**
 * Registers the block from the block.json in /build/block.
 */
function icon_library_register_block()
{
    register_block_type(__DIR__ . '/build/block');
}
add_action('init', 'icon_library_register_block');

/**
 * Loads the plugin translations.
 */
function icon_library_load_textdomain()
{
    load_plugin_textdomain('icon-library', false, dirname(plugin_basename(__FILE__)) . '/languages');
}
add_action('init', 'icon_library_load_textdomain');

/**
 * Provides the sprite URL to the editor as window.iconLibrarySettings.spriteUrl.
 *
 * Runs on enqueue_block_editor_assets so that the editorScript generated by
 * register_block_type (handle: icon-library-svg-fragment-editor-script)
 * is already registered.
 */
function icon_library_editor_assets()
{
    wp_localize_script(
        'icon-library-svg-fragment-editor-script',
        'iconLibrarySettings',
        ['spriteUrl' => icon_library_sprite_url()],
    );
}
add_action('enqueue_block_editor_assets', 'icon_library_editor_assets');
